// old makenl config file errors.

enum logtxt
{
	CF_MAKE,
	CF_NAME,
	CF_PUBLISH,
	CF_PROCESS,
	CF_MERGE,
	CF_PRIVATE,
	CF_MINPHONE,
	CF_BAUDRATE,
	CF_MASTER,
	CF_UPLOADS,                //10
	CF_MAILFILES,
	CF_UPDATE,
	CF_BADFILES,
	CF_OUTFILE,
	CF_OUTPATH,
	CF_THRESHOLD,
	CF_ARC,
	CF_OUTDIFF,
	CF_CLEANUP,
	CF_NETADDRESS,             //20
	CF_MESSAGES,
	CF_SUBMIT,
	CF_NOTIFY,
	CF_COPYRIGHT,
	CF_PROLOG,
	CF_EPILOG,
	CF_COMMENTS,
	CF_DATA,
	CF_FILES,
	CF_FLAGS,
	CF_PVTLEVEL,
	CFE_ABORT,                 //30 add one
	CFE_MAKE,                  //30
	CFE_NAME,
	CFE_PUBLISH,
	CFE_PROCESS,
	CFE_MERGE,
	CFE_PRIVATE,
	CFE_MINPHONE,
	CFE_BAUDRATE,
	CFE_MASTER,
	CFE_UPLOADS,
	CFE_MAILFILES,             //40
	CFE_UPDATE,
	CFE_BADFILES,
	CFE_OUTFILE,
	CFE_OUTPATH,
	CFE_THRESHOLD,
	CFE_ARC,
	CFE_OUTDIFF,
	CFE_CLEANUP,
	CFE_NETADDRESS,
	CFE_NETADDRESS_INV,
	CFE_MESSAGES,               //50
	CFE_SUBMIT,
	CFE_NOTIFY,
	CFE_COPYRIGHT,
	CFE_PROLOG,
	CFE_EPILOG,
	CFE_COMMENTS,
	CFE_DATA,
	CFE_DATA_COM,
	CFE_FILES,
	CFE_FILES_STYPE,              //60
	CFE_FILES_NAME,
	CFE_LOGLEVEL,
	CFE_COMPRESS,
	CFE_PVTLEVEL,
	CFE_ERR_BAD,
	SYS_START,
	SYS_STOP,
	SYS_CF_PROC,
	SYS_COMMAND,
	SYS_COMMAND_ABORT,
	CFE_MAXAGE,
	CFE_MAXFILES
};

#define YES  1
#define NO   0
// Max Values

#define MAXSTR   512

